-------------------
--frostwyrm frosty scale --apply frosty scale buff to frostwyrm making her take 45/70/95% less damage from physical  + slowing any attacker stacking. Reflect frost damage * stack count on attack.
-------------------
-------------------
--frostwyrm magic suppressor -- apply magic suppressor aura to frostwyrm increasing her debuff resistance to 100%. Reducing enemy spell damage, healing cause by 45/70/95% and buff amplification by 50%. Each spell casted by enemy nearby will damage the caster + small aoe around the caster + apply debuff counter. Damage more on subsequent cast depend on number of debuff counter caster has.
-------------------
--particles/econ/items/crystal_maiden/ti9_immortal_staff/cm_ti9_staff_lvlup_globe_spawn.vpcf
-------------------
--frostwyrm aerial onslaught --become invul + fly around the battlefield trying to go above every hero dropping arctic bomb dealing very high frost damage
-------------------
-------------------
--frostwyrm ice beam -- low cd sunray like ability that rotate for 180 degrees. Instant kill frozen enemy.
-------------------
-------------------
--frostwyrm frost wall -- launch linear projectiles spawning impassable ice wall. Enemy standing too close to ice wall get slow + frost damage. Frostwyrm can move above icewall.
-------------------
-------------------
--frostwyrm freezing breath --passive splash attack dealing frost and every 4th attack will apply frozen status in a small aoe.
-------------------
-------------------
--frostwyrm chill baby --apply frozen status to all hero nearby but 1. frozen hero is stunned + sealing frostbite until rescue/dispel. Each second frozen hero take % low health damage. Rescue by staying close to frozen hero for 2s.
-------------------
-------------------
--frostwyrm eternal winter --passive low damage per second + apply stacking low ms reduction debuff every sec when her health drop, the damage + slow increase when her health drop more.
-------------------