require("creeps/zone1/boss/brood")
require("creeps/zone1/boss/lycan")
require("creeps/zone1/boss/treant")
require("creeps/zone1/boss/ursa")
require("creeps/zone1/boss/luna")
require("creeps/zone1/boss/mirana")
require("creeps/zone1/boss/venge")
