local prefix = "heroes/"
require(prefix.."hero_blazing_berserker")
require(prefix.."hero_chosen_invoker")
require(prefix.."hero_crystal_sorceress")
require(prefix.."hero_light_cardinal")
require(prefix.."hero_molten_guardian")
require(prefix.."hero_phantom_ranger")
require(prefix.."hero_priestess_of_sacred_forest")
require(prefix.."hero_terror_lord")
require(prefix.."hero_luminous_samurai")